-- ============================================================
--  Akagera Inc - starter seed data  (run AFTER akagerainc_schema.sql)
--  mysql -u USER -p akagerainc < seed.sql
--
--  NOTE: `python seed.py` produces a richer seed (admin user, demo
--  services with dynamic fields, demo products, blog, etc). This SQL
--  file covers site content + navigation + a minimal catalog so the
--  site renders immediately.
-- ============================================================
-- (select your database first, e.g.  USE your_db_name;)

INSERT INTO site_content (content_key, content_value) VALUES ('brand', '{"name": "Akagera Inc", "tagline": "Technology solutions built for what comes next.", "primary_color": "#BD4A39", "ink": "#141414", "paper": "#FFFFFF", "logo": "/assets/inc.png"}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('hero', '{"kicker": "Akagera Inc \\u2014 Software Solutions", "title": "Technology Solutions Built for What Comes Next.", "subtitle": "Akagera Inc builds mobile apps, websites, desktop software, SaaS products, and custom digital solutions that help individuals, businesses, and organizations turn ideas into reliable technology.", "primary_cta": {"label": "Explore Our Solutions", "url": "/solutions"}, "secondary_cta": {"label": "Start a Project", "url": "/contact?intent=project"}}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('homepage_sections', '[{"key": "hero", "label": "Hero", "enabled": true, "order": 1}, {"key": "product_grid", "label": "Software built by Akagera Inc", "enabled": true, "order": 2}, {"key": "featured_products", "label": "Featured Akagera Products", "enabled": true, "order": 3}, {"key": "services", "label": "Services", "enabled": true, "order": 4}, {"key": "industries", "label": "Industries", "enabled": true, "order": 5}, {"key": "stats", "label": "Statistics", "enabled": true, "order": 6}, {"key": "case_studies", "label": "Our Work", "enabled": true, "order": 7}, {"key": "testimonials", "label": "Testimonials", "enabled": true, "order": 8}, {"key": "blog", "label": "From the blog", "enabled": true, "order": 9}, {"key": "cta", "label": "Call to action", "enabled": true, "order": 10}, {"key": "location", "label": "Our location", "enabled": true, "order": 11}]') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('product_categories', '[{"name": "Mobile Applications", "slug": "mobile", "icon": "smartphone", "description": "Apps built for Android and iOS.", "platforms": ["android", "ios"]}, {"name": "Web Applications", "slug": "web", "icon": "globe", "description": "Modern responsive web platforms.", "platforms": ["web"]}, {"name": "Windows Software", "slug": "windows", "icon": "monitor", "description": "Native, professional Windows applications.", "platforms": ["windows"]}, {"name": "macOS Software", "slug": "macos", "icon": "command", "description": "Software designed for Apple''s desktop ecosystem.", "platforms": ["macos"]}, {"name": "SaaS Platforms", "slug": "saas", "icon": "cloud", "description": "Cloud-based software available through subscriptions.", "platforms": ["cloud"]}, {"name": "Custom Software", "slug": "custom", "icon": "layers", "description": "Software designed specifically for organizations and businesses.", "platforms": []}]') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('social_links', '{"linkedin": "https://www.linkedin.com/company/akagera-inc", "github": "https://github.com/akagerainc-boop", "x": "https://x.com/akagerainc", "facebook": "https://www.facebook.com/akagerainc", "instagram": "https://www.instagram.com/akagerainc", "youtube": "https://www.youtube.com/@akagerainc"}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('contact_info', '{"email": "akagerainc@gmail.com", "support_email": "support@akagerainc.store", "sales_email": "sales@akagerainc.store", "phone": "+250 795 226 123", "whatsapp": "250795226123", "address_lines": ["Innovation Hub Building", "Main Street, Musanze District", "Northern Province, Rwanda"], "hours": ["Monday - Friday: 8:00 AM - 6:00 PM", "Saturday: 9:00 AM - 1:00 PM", "Sunday: Closed"], "map_query": "Musanze,Rwanda"}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('company_info', '{"who_we_are": "Akagera Inc is a technology and software solutions company. We design, build, and maintain software across mobile, web, desktop, and cloud \\u2014 for individuals, businesses, and organizations.", "mission": "To create useful, scalable, and reliable technology that helps people and organizations do more.", "vision": "A connected Africa where every organization runs on software it can trust.", "values": ["Reliability", "Craft", "Transparency", "Long-term thinking", "Customer obsession"], "founded": "2021", "headquarters": "Musanze, Rwanda"}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('whatsapp', '{"number": "250795226123", "message": "Hello Akagera Inc, I''d like to talk about a project."}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('pricing', '[{"name": "Starter", "price": "$49", "currency": "USD", "duration": "30-day service", "popular": false, "description": "For a focused piece of work with a clear scope.", "features": ["Basic support", "1 project", "30-day delivery window", "Source handover"]}, {"name": "Professional", "price": "$199", "currency": "USD", "duration": "90-day service", "popular": true, "description": "For growing teams that need more surface area and priority help.", "features": ["Priority support", "Multiple features", "Priority assistance", "2 revision rounds", "Deployment"]}, {"name": "Enterprise", "price": "Custom", "currency": "USD", "duration": "Ongoing", "popular": false, "description": "For organizations needing dedicated delivery and SLAs.", "features": ["Dedicated team", "Advanced security", "SLA", "API integration", "Onboarding & training"]}]') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('seo_defaults', '{"title": "Akagera Inc \\u2014 Software Solutions", "description": "Akagera Inc builds software, sells digital products and services, publishes applications, and provides licenses, subscriptions, and professional technology solutions.", "og_image": "/assets/inc.png", "site_url": "https://akagerainc.store"}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('industries_intro', '{"title": "Industry solutions", "subtitle": "Software patterns we''ve shipped across sectors."}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('legal_privacy', '{"title": "Privacy Policy", "updated": "2026-01-01", "body": "Akagera Inc collects only the information needed to deliver its products and services. We never sell your data. Contact privacy@akagerainc.store for requests."}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('legal_terms', '{"title": "Terms of Service", "updated": "2026-01-01", "body": "By using this website and its services you agree to Akagera Inc''s terms. Services are delivered according to the scope and duration shown at purchase."}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('legal_refund', '{"title": "Refund Policy", "updated": "2026-01-01", "body": "Digital services may be refunded within 14 days if work has not started. Licenses and subscriptions are refundable within 14 days if unused."}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);
INSERT INTO site_content (content_key, content_value) VALUES ('legal_cookie', '{"title": "Cookie Policy", "updated": "2026-01-01", "body": "We use essential cookies for authentication and a minimal set of analytics cookies. You can decline non-essential cookies."}') ON DUPLICATE KEY UPDATE content_value = VALUES(content_value);

INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Products','/products',1,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Mobile Apps','/products?category=mobile',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Web Applications','/products?category=web',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Windows Software','/products?category=windows',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'macOS Software','/products?category=macos',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'SaaS Products','/products?category=saas',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Enterprise Software','/products?category=enterprise',5,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Developer Tools','/products?category=developer-tools',6,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Digital Products','/products?category=digital',7,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'All Products','/products',8,1);
INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Solutions','/solutions',2,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Business Solutions','/solutions/business',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Enterprise Solutions','/solutions/enterprise',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Education Solutions','/solutions/education',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Startup Solutions','/solutions/startup',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'E-commerce Solutions','/solutions/ecommerce',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Automation Solutions','/solutions/automation',5,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Cloud Solutions','/solutions/cloud',6,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Custom Software','/solutions/custom-software',7,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Digital Transformation','/solutions/digital-transformation',8,1);
INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Services','/services',3,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Mobile App Development','/services',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Web Development','/services',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Desktop Application Development','/services',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'UI/UX Design','/services',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Backend Development','/services',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'API Development','/services',5,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Database Development','/services',6,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Cloud Development','/services',7,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Software Maintenance','/services',8,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'App Publishing','/services',9,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Software Consulting','/services',10,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Technical Support','/services',11,1);
INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Downloads','/downloads',4,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Android APK','/downloads?platform=android',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'iOS Apps','/downloads?platform=ios',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Windows Apps','/downloads?platform=windows',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'macOS Apps','/downloads?platform=macos',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Software Releases','/downloads',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Release Notes','/downloads?view=notes',5,1);
INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Resources','/documentation',5,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Documentation','/documentation',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Blog','/blog',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Tutorials','/documentation?section=tutorials',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Case Studies','/case-studies',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'FAQs','/support?view=faq',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Help Center','/support',5,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Developer Resources','/documentation?section=developers',6,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'System Requirements','/documentation?section=system-requirements',7,1);
INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Company','/about',6,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'About Akagera Inc','/about',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Careers','/careers',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Internships','/internships',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Portfolio','/portfolio',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Contact','/contact',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,sort_order,is_enabled) VALUES ('header',@p,'Business Portal','/business',5,1);
INSERT INTO navigation_items (location,label,url,sort_order,is_enabled) VALUES ('header','Pricing','/pricing',7,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,label,column_group,sort_order,is_enabled) VALUES ('footer','Products','Products',0,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Mobile Apps','/products?category=mobile','Products',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Web Apps','/products?category=web','Products',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Windows Apps','/products?category=windows','Products',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'macOS Apps','/products?category=macos','Products',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'SaaS','/products?category=saas','Products',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'All Products','/products','Products',5,1);
INSERT INTO navigation_items (location,label,column_group,sort_order,is_enabled) VALUES ('footer','Services','Services',1,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'App Development','/services','Services',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Web Development','/services','Services',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Desktop Development','/services','Services',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'UI/UX','/services','Services',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Cloud','/services','Services',4,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Consulting','/services','Services',5,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Maintenance','/services','Services',6,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Support','/support','Services',7,1);
INSERT INTO navigation_items (location,label,column_group,sort_order,is_enabled) VALUES ('footer','Company','Company',2,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'About','/about','Company',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Careers','/careers','Company',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Internships','/internships','Company',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Portfolio','/portfolio','Company',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Contact','/contact','Company',4,1);
INSERT INTO navigation_items (location,label,column_group,sort_order,is_enabled) VALUES ('footer','Resources','Resources',3,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Blog','/blog','Resources',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Documentation','/documentation','Resources',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Help Center','/support','Resources',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'FAQs','/support?view=faq','Resources',3,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Release Notes','/downloads?view=notes','Resources',4,1);
INSERT INTO navigation_items (location,label,column_group,sort_order,is_enabled) VALUES ('footer','Legal','Legal',4,1);
SET @p = LAST_INSERT_ID();
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Privacy Policy','/privacy','Legal',0,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Terms of Service','/terms','Legal',1,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Refund Policy','/refund-policy','Legal',2,1);
INSERT INTO navigation_items (location,parent_id,label,url,column_group,sort_order,is_enabled) VALUES ('footer',@p,'Cookie Policy','/cookie-policy','Legal',3,1);

INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('education','Education','graduation-cap','School management, e-learning, and student platforms.',1,0);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('finance','Finance','banknote','Payments, lending, and financial operations software.',1,1);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('healthcare','Healthcare','heart-pulse','Clinic, pharmacy, and patient record systems.',1,2);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('retail','Retail','shopping-bag','POS, inventory, and e-commerce platforms.',1,3);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('transportation','Transportation','truck','Fleet, logistics, and mobility solutions.',1,4);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('hospitality','Hospitality','bed','Hotel, restaurant, and booking systems.',1,5);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('government','Government','landmark','Citizen services and public-sector digital platforms.',1,6);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('startups','Startups','rocket','MVPs and product engineering for founders.',1,7);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('small-business','Small Businesses','store','Affordable websites and business tools.',1,8);
INSERT INTO industries (slug,name,icon,summary,is_active,sort_order) VALUES ('enterprises','Enterprises','building-2','Custom enterprise software and integrations.',1,9);
